builds:
  - id: main
    main: main.go
    binary: "exoscale-account-wiper"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - builds:
      - main
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "janoszen/{{.ProjectName}}:latest"
      - "janoszen/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
      - "janoszen/{{.ProjectName}}:{{ .Tag }}"
      - "docker.pkg.github.com/janoszen/exoscale-account-wiper/{{.ProjectName}}:latest"
      - "docker.pkg.github.com/janoszen/exoscale-account-wiper/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/janoszen/exoscale-account-wiper/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    builds:
      - main
    extra_files:
      - LICENSE.md
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: auto
dist: build
release:
  github:
    owner: janoszen
    name: exoscale-account-wiper
  prerelease: auto
